server:
  port: ${PORT}
application:
  id: ${APPLICATION_ID}
kafka:
  enableViewMaterialization: ${ENABLE_VIEW_MATERIALIZATION}
  url: ${spring.embedded.kafka.brokers} # ${KAFKA_URL}
  bootstrap-servers: ${spring.embedded.kafka.brokers}
  schemaRegistryUrl: ${SCHEMA_REGISTRY_URL}
