#!/bin/bash

ROOT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"

if [[ -d ~/.bash_it ]]; then
    echo "Bash it is already installed."
else
    git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
    ~/.bash_it/install.sh --silent

    cp ~/.bash_profile ~/.bash_profile ~/.bash_profile.bash_it.bak
    cp $ROOT_DIRECTORY/setup/bash_it/.bash_profile ~/.bash_profile
fi

