kafka:
  url: http://localhost:9092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kappa_architecture_development
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect