#!/bin/bash

WORKSTATION_SETUP_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

ensure_in_bash_profile() {
    LINE=$1
    FILE=~/.bash_profile

    touch "${FILE}"
    grep -q "${LINE}" "${FILE}" || echo "${LINE}" >> "${FILE}"
}

ensure_in_bash_profile "source $WORKSTATION_SETUP_DIRECTORY/bash_profile"
