#!/bin/bash

SCRIPTS_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/scripts" && pwd )"

$SCRIPTS_DIRECTORY/homebrew
$SCRIPTS_DIRECTORY/bash_it
$SCRIPTS_DIRECTORY/brew_bundle
$SCRIPTS_DIRECTORY/ruby
