#!/bin/bash

SETUP_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${SETUP_DIRECTORY}/support/ensure_formula_installed

ensure_formula_installed "postgres"
brew services start postgres

createdb kappa_architecture_development
createdb kappa_architecture_test
