#!/bin/bash

SETUP_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${SETUP_DIRECTORY}/support/ensure_formula_installed

ensure_formula_installed "postgres"
brew services start postgres

createdb consumer_development
createdb consumer_test